// Generated by Xata Codegen 0.29.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type { BaseClientOptions, SchemaInference, XataRecord } from "@xata.io/client";

const tables = [
  {
    name: "works",
    columns: [
      { name: "images", type: "file[]" },
      { name: "price", type: "float", notNull: true, defaultValue: "0.0" },
      { name: "name", type: "string", notNull: true, defaultValue: "Anon" },
      {
        name: "description",
        type: "string",
        notNull: true,
        defaultValue: "Anon",
      },
      { name: "author", type: "link", link: { table: "authors" } },
    ],
  },
  {
    name: "authors",
    columns: [
      { name: "name", type: "string", notNull: true, defaultValue: "Anon" },
      { name: "art_name", type: "string", unique: true },
      { name: "description", type: "string" },
      { name: "surname", type: "string", notNull: true, defaultValue: "Anon" },
    ],
    revLinks: [{ column: "author", table: "works" }],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Works = InferredTypes["works"];
export type WorksRecord = Works & XataRecord;

export type Authors = InferredTypes["authors"];
export type AuthorsRecord = Authors & XataRecord;

export type DatabaseSchema = {
  works: WorksRecord;
  authors: AuthorsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://Alejandro-Sierro-s-workspace-gjdu7j.eu-central-1.xata.sh/db/project-mz",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient({
    apiKey: import.meta.env.XATA_API_KEY,
    branch: import.meta.env.XATA_BRANCH,
  });
  return instance;
};
